import io
import json
import logging
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

logger = logging.getLogger(__name__)

def export_blueprint_to_markdown(blueprint_data: Dict[str, Any], idea_title: str) -> str:
    """Generate a clean, comprehensive Markdown report of the complete Startup Blueprint."""
    md = []
    md.append(f"# Startup Blueprint: {idea_title}\n")
    md.append("*Generated by AI Startup Builder Multi-Agent Pipeline*\n\n---\n")

    # 1. Validation
    val = blueprint_data.get("validation", {})
    if val:
        md.append("## 1. Idea Validation & Feasibility Report\n")
        md.append(f"- **Problem**: {val.get('problem')}")
        md.append(f"- **Solution**: {val.get('solution')}")
        md.append(f"- **Feasibility Score**: {val.get('feasibility_score')}/100")
        md.append(f"- **Innovation Score**: {val.get('innovation_score')}/100")
        md.append(f"- **Market Viability Score**: {val.get('market_viability_score')}/100\n")
        md.append("### Key Strengths")
        for s in val.get("strengths", []):
            md.append(f"- {s}")
        md.append("\n### Key Weaknesses")
        for w in val.get("weaknesses", []):
            md.append(f"- {w}")
        md.append("\n### Actionable Suggestions")
        for sug in val.get("suggestions", []):
            md.append(f"- {sug}")
        md.append(f"\n> **Meflex Reflection Notes**: {val.get('reflection_notes')}\n\n---\n")

    # 2. Market Research
    mkt = blueprint_data.get("market", {})
    if mkt:
        md.append("## 2. Market Research & TAM Analysis\n")
        md.append(f"- **Industry**: {mkt.get('industry')}")
        md.append(f"- **Market Size**: {mkt.get('market_size')}")
        md.append(f"- **TAM (Total Addressable Market)**: {mkt.get('tam')}")
        md.append(f"- **SAM (Serviceable Addressable Market)**: {mkt.get('sam')}")
        md.append(f"- **SOM (Serviceable Obtainable Market)**: {mkt.get('som')}")
        md.append(f"- **Target Market Segment**: {mkt.get('target_market')}\n")
        md.append("### Key Market Trends")
        for t in mkt.get("trends", []):
            md.append(f"- {t}")
        md.append("\n### Market Opportunities")
        for opp in mkt.get("opportunities", []):
            md.append(f"- {opp}")
        md.append("\n### Market Challenges & Entry Barriers")
        for ch in mkt.get("challenges", []):
            md.append(f"- {ch}\n\n---\n")

    # 3. Competitor Analysis
    comp = blueprint_data.get("competitors", {})
    if comp:
        md.append("## 3. Competitive Landscape & Market Gap\n")
        md.append(f"**Validation Judge Summary**: {comp.get('validation_summary')}\n")
        md.append("### Top Competitors")
        for c in comp.get("competitors", []):
            md.append(f"#### {c.get('name')} ({c.get('category')})")
            md.append(f"- **Pricing**: {c.get('pricing')}")
            md.append(f"- **Strengths**: {', '.join(c.get('strengths', []))}")
            md.append(f"- **Weaknesses**: {', '.join(c.get('weaknesses', []))}")
            md.append(f"- **Market Gap Left Open**: {c.get('market_gap')}\n")
        md.append("### Key Differentiators for Your Startup")
        for diff in comp.get("key_differentiators", []):
            md.append(f"- {diff}\n\n---\n")

    # 4. Customer Persona
    persona = blueprint_data.get("persona", {})
    if persona:
        md.append("## 4. Target Customer Persona\n")
        md.append(f"- **Persona Name**: {persona.get('persona_name')}")
        md.append(f"- **Target Age Bracket**: {persona.get('age')}")
        md.append(f"- **Occupation**: {persona.get('occupation')}\n")
        md.append("### Pain Points")
        for p in persona.get("pain_points", []):
            md.append(f"- {p}")
        md.append("\n### Goals & Aspirations")
        for g in persona.get("goals", []):
            md.append(f"- {g}")
        md.append(f"\n- **Behavior Patterns**: {persona.get('behaviour')}")
        md.append("\n### Buying Triggers")
        for trig in persona.get("buying_triggers", []):
            md.append(f"- {trig}\n\n---\n")

    # 5. Business Model
    bm = blueprint_data.get("business_model", {})
    if bm:
        md.append("## 5. Monetization & Business Model\n")
        md.append(f"- **Revenue Model**: {bm.get('revenue_model')}")
        md.append(f"- **Value Proposition**: {bm.get('value_proposition')}")
        md.append(f"- **Unit Economics**: {bm.get('unit_economics')}")
        md.append(f"- **Cost Structure**: {bm.get('cost_structure')}\n")
        md.append("### Pricing Tiers")
        for tier in bm.get("pricing_tiers", []):
            md.append(f"- {tier}")
        md.append("\n### Distribution Channels")
        for ch in bm.get("channels", []):
            md.append(f"- {ch}\n\n---\n")

    # 6. MVP Scope
    mvp = blueprint_data.get("mvp", {})
    if mvp:
        md.append("## 6. MVP Product Roadmap & Tech Stack\n")
        md.append(f"- **Estimated Timeline**: {mvp.get('timeline_weeks')} weeks to launch MVP\n")
        md.append("### Phase 1 MVP Core Features")
        for feat in mvp.get("core_features", []):
            md.append(f"- [x] {feat}")
        md.append("\n### Phase 2/3 Scaling Features")
        for fut in mvp.get("future_features", []):
            md.append(f"- [ ] {fut}")
        md.append("\n### Recommended Technology Stack")
        for tech in mvp.get("recommended_tech_stack", []):
            md.append(f"- {tech}\n\n---\n")

    # 7. Financial Planning
    fin = blueprint_data.get("financial", {})
    if fin:
        md.append("## 7. Financial Projections & Unit Economics\n")
        md.append(f"- **Estimated Initial Capital Needed**: {fin.get('estimated_cost')}")
        md.append(f"- **Monthly Operational Burn Rate**: {fin.get('monthly_expense')}")
        md.append(f"- **Projected Revenue**: {fin.get('expected_revenue')}")
        md.append(f"- **Break-Even Timeframe**: {fin.get('break_even_months')} months")
        md.append(f"- **Projected 3-Year ROI**: {fin.get('roi_estimate')}")
        md.append(f"- **Financial Notes**: {fin.get('financial_risks_note')}\n\n---\n")

    # 8. Risk Assessment
    risk = blueprint_data.get("risk", {})
    if risk:
        md.append("## 8. Risk Assessment & Mitigation Strategies\n")
        md.append(f"- **Technical Risk**: {risk.get('technical_risk')}")
        md.append(f"- **Financial Risk**: {risk.get('financial_risk')}")
        md.append(f"- **Legal & Compliance Risk**: {risk.get('legal_risk')}")
        md.append(f"- **Market Risk**: {risk.get('market_risk')}\n")
        md.append("### Mitigation Playbook")
        for mit in risk.get("mitigation_strategies", []):
            md.append(f"- {mit}\n\n---\n")

    # 9. Marketing Strategy
    mktg = blueprint_data.get("marketing", {})
    if mktg:
        md.append("## 9. Marketing & Go-To-Market (GTM) Strategy\n")
        md.append(f"- **Brand Positioning**: {mktg.get('branding_identity')}")
        md.append(f"- **Customer Acquisition Playbook**: {mktg.get('customer_acquisition_strategy')}")
        md.append(f"- **CAC vs LTV Benchmarks**: {mktg.get('cac_ltv_benchmarks')}\n")
        md.append("### Primary Marketing Channels")
        for ch in mktg.get("marketing_channels", []):
            md.append(f"- {ch}")
        md.append("\n### 90-Day Product Launch Plan")
        for lp in mktg.get("launch_plan_90_days", []):
            md.append(f"- {lp}\n\n---\n")

    # 10. Pitch Deck
    pitch = blueprint_data.get("pitch", {})
    if pitch:
        md.append("## 10. Investor Pitch Deck Structure (10 Slides)\n")
        md.append(f"- **Pitch Title**: {pitch.get('title')}")
        md.append(f"- **Tagline**: {pitch.get('tagline')}")
        md.append(f"- **Executive Summary**: {pitch.get('presentation_summary')}")
        md.append(f"- **Investment Ask**: {pitch.get('ask_amount')}\n")
        for slide in pitch.get("slides", []):
            md.append(f"### Slide {slide.get('slide_number')}: {slide.get('title')}")
            for b in slide.get("bullet_points", []):
                md.append(f"  * {b}")
            md.append(f"  * **Key Takeaway**: {slide.get('key_takeaway')}")
            md.append(f"  * *Speaker Notes*: {slide.get('speaker_notes')}\n")

    return "\n".join(md)

def export_blueprint_to_pdf(blueprint_data: Dict[str, Any], idea_title: str) -> bytes:
    """Generate an investor-ready PDF document bytes using ReportLab."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=22,
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=12
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=18
    )
    h2_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=15,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=14,
        spaceAfter=8
    )
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['BodyText'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#334155"),
        spaceAfter=6
    )
    bold_body_style = ParagraphStyle(
        'BoldBodyCustom',
        parent=styles['BodyText'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#0f172a"),
        fontName="Helvetica-Bold",
        spaceAfter=6
    )

    story = []
    
    # Title Block
    story.append(Paragraph(f"AI Startup Blueprint: {idea_title}", title_style))
    story.append(Paragraph("Generated by AI Startup Builder - Multi-Agent Intelligent Platform", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#3b82f6"), spaceAfter=14))

    # Helper function to append section
    def add_section(title: str, items: list):
        story.append(Paragraph(title, h2_style))
        for key, val in items:
            if isinstance(val, list):
                story.append(Paragraph(f"<b>{key}:</b>", bold_body_style))
                for v in val:
                    story.append(Paragraph(f"• {v}", body_style))
            else:
                story.append(Paragraph(f"<b>{key}:</b> {val}", body_style))
        story.append(Spacer(1, 8))

    # 1. Validation
    val = blueprint_data.get("validation", {})
    if val:
        add_section("1. Idea Validation & Feasibility Report", [
            ("Problem", val.get("problem", "")),
            ("Solution", val.get("solution", "")),
            ("Feasibility Score", f"{val.get('feasibility_score', 0)} / 100"),
            ("Innovation Score", f"{val.get('innovation_score', 0)} / 100"),
            ("Market Viability Score", f"{val.get('market_viability_score', 0)} / 100"),
            ("Strengths", val.get("strengths", [])),
            ("Weaknesses", val.get("weaknesses", [])),
            ("Suggestions", val.get("suggestions", [])),
            ("Reflection Notes", val.get("reflection_notes", ""))
        ])

    # 2. Market
    mkt = blueprint_data.get("market", {})
    if mkt:
        add_section("2. Market Research & TAM Analysis", [
            ("Industry", mkt.get("industry", "")),
            ("Market Size", mkt.get("market_size", "")),
            ("TAM / SAM / SOM", f"TAM: {mkt.get('tam')} | SAM: {mkt.get('sam')} | SOM: {mkt.get('som')}"),
            ("Target Market", mkt.get("target_market", "")),
            ("Trends", mkt.get("trends", [])),
            ("Opportunities", mkt.get("opportunities", [])),
            ("Challenges", mkt.get("challenges", []))
        ])

    # 3. Competitors
    comp = blueprint_data.get("competitors", {})
    if comp:
        add_section("3. Competitor Landscape & Differentiation", [
            ("Validation Judge Summary", comp.get("validation_summary", "")),
            ("Key Differentiators", comp.get("key_differentiators", []))
        ])

    # 4. Financials
    fin = blueprint_data.get("financial", {})
    if fin:
        add_section("4. Financial Estimates & ROI", [
            ("Estimated Setup Cost", fin.get("estimated_cost", "")),
            ("Monthly Burn Rate", fin.get("monthly_expense", "")),
            ("Projected Revenue", fin.get("expected_revenue", "")),
            ("Break-Even", f"{fin.get('break_even_months', 0)} months"),
            ("Projected 3-Year ROI", fin.get("roi_estimate", ""))
        ])

    # 5. Pitch Deck Summary
    pitch = blueprint_data.get("pitch", {})
    if pitch:
        add_section("5. Pitch Deck Overview", [
            ("Title", pitch.get("title", "")),
            ("Tagline", pitch.get("tagline", "")),
            ("Summary", pitch.get("presentation_summary", "")),
            ("Investment Ask", pitch.get("ask_amount", ""))
        ])

    doc.build(story)
    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data
